os:
  - linux
sudo: required
language: php
php:
  - 7.2
services:
  - docker
install:
  # worksace
  - wget https://my127.io/workspace/ws && chmod +x ws && sudo mv ws /usr/local/bin/ws
  # splitsh-lite
  - wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
  - sudo tar -zxpf lite_linux_amd64.tar.gz --directory /usr/local/bin/
script:
  - |
    # harness-drupal8
    ws create test inviqa/drupal8 --no-install && cd test && cp -ap dist/harness-drupal8 ./.my127ws
    ws install
    ws destroy
    cd .. && rm -rf test
after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "0.1.x" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      ./deploy
    fi
