os:
  - linux
sudo: required
language: php
php:
  - 7.2
services:
  - docker
install:
  - wget https://my127.io/workspace/ws && chmod +x ws && sudo mv ws /usr/local/bin/ws
script:
  - ./build
  - |
    # harness-drupal8
    ws create test inviqa/drupal8 --no-install && cd test && cp -ap _build/harness-drupal8 ./.my127ws
    ws install
    ws destroy
    cd .. && rm -rf test
  - |
    # harness-magento1
    cp -ap _build/harness-magento1/.ci/sample ./test && cd test && cp -ap _build/harness-magento2 ./.my127ws
    ws install
    ws destroy
    cd .. && rm -rf test
  - |
    # harness-magento2
    cp -ap _build/harness-magento2/.ci/sample ./test && cd test && cp -ap _build/harness-magento1 ./.my127ws
    ws install
    ws destroy
    cd .. && rm -rf test
  - |
    # harness-wordpress
    cp -ap _build/harness-wordpress/.ci/sample ./test && cd test && cp -ap _build/harness-wordpress ./.my127ws
    ws install
    ws destroy
    cd .. && rm -rf test
