#!/bin/bash

set -e
set -x

HARNESSES=(harness-drupal8 harness-magento1 harness-magento2 harness-wordpress)

function main()
{
    for harness in "${HARNESSES[@]}"
    do
        build $harness
    done
}

function build()
{
    local harness="$1"

    if [[ ! -d "$harness" ]]; then
        echo "harness '${harness}' not found."
    fi

    local harness_build_path="./_build/${harness}/"
    local harness_src_path="./${harness}/"

    if [[ -d "$harness_build_path" ]]; then
        rm -rf "$harness_build_path"
    fi

    mkdir "$harness_build_path"

    rsync -va "./base/" "$harness_build_path"
    rsync -va "$harness_src_path" "$harness_build_path"
}

main
