#!/bin/bash

set -e
set -x

HARNESSES=(harness-drupal8 harness-magento1 harness-magento2 harness-wordpress)

function main()
{
    local branch="$1"
    local message="$2"

    for harness in "${HARNESSES[@]}"
    do
        publish "$harness" "$branch" "$message"
    done
}

function publish()
{
    local harness="$1"
    local branch="$2"
    local message="$3"

    if [[ ! -d "$harness" ]]; then
        echo "harness '${harness}' not found."
    fi

    local harness_publish_path="./_publish/${harness}/"

    if [[ -d "$harness_publish_path" ]]; then
        rm -rf "$harness_publish_path"
    fi

    (
        cd ./_publish
        git clone git@github.com:inviqa/${harness}.git
        rsync -avC --delete ../_build/${harness}/ ./${harness}
        cd ./${harness}
        git checkout -b "$branch"
        git add .
        git commit -m "$message"
    )
}

./build
main "$1" "$2"
